name: contrust_workspace
publish_to: none
environment:
  sdk: ">=3.9.0 <4.0.0"

flutter:
  uses-material-design: true

workspace:
  - Back-End
  - Contractee
  - Contractor
  - SuperAdmin
  - websitepoint

assets: 
  - assets/bgloginscreen.jpg
